# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20180306_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json1', jsonfield.fields.JSONField(max_length=200)),
                ('json2', jsonfield.fields.JSONField(max_length=200)),
                ('json3', jsonfield.fields.JSONField(max_length=200)),
                ('json4', jsonfield.fields.JSONField(max_length=200)),
                ('json5', jsonfield.fields.JSONField(max_length=200)),
                ('json6', jsonfield.fields.JSONField(max_length=200)),
                ('json7', jsonfield.fields.JSONField(max_length=200)),
                ('json8', jsonfield.fields.JSONField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='level',
            name='json',
        ),
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 3, 6, 13, 24, 25, 912229)),
        ),
    ]
