# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0014_auto_20180306_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iMinX', models.IntegerField()),
                ('iMinY', models.IntegerField()),
                ('iMaxX', models.IntegerField()),
                ('iMaxY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=20)),
                ('b', models.CharField(max_length=20)),
                ('c', models.CharField(max_length=20)),
                ('d', models.CharField(max_length=20)),
                ('e', models.CharField(max_length=20)),
                ('f', models.CharField(max_length=20)),
                ('g', models.CharField(max_length=20)),
                ('h', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='fields',
        ),
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 3, 6, 20, 2, 9, 26303)),
        ),
    ]
