# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0015_auto_20180306_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='index',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='show.images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='show.level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 3, 6, 20, 24, 38, 950921)),
        ),
    ]
