# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0018_auto_20180306_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='dimension1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=20)),
                ('iMinX', models.IntegerField()),
                ('iMinY', models.IntegerField()),
                ('iMaxX', models.IntegerField()),
                ('iMaxY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dimension2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.CharField(max_length=20)),
                ('iMinX', models.IntegerField()),
                ('iMinY', models.IntegerField()),
                ('iMaxX', models.IntegerField()),
                ('iMaxY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dimension3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.CharField(max_length=20)),
                ('iMinX', models.IntegerField()),
                ('iMinY', models.IntegerField()),
                ('iMaxX', models.IntegerField()),
                ('iMaxY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dimension4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.CharField(max_length=20)),
                ('iMinX', models.IntegerField()),
                ('iMinY', models.IntegerField()),
                ('iMaxX', models.IntegerField()),
                ('iMaxY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dimension5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.CharField(max_length=20)),
                ('iMinX', models.IntegerField()),
                ('iMinY', models.IntegerField()),
                ('iMaxX', models.IntegerField()),
                ('iMaxY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dimension6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(max_length=20)),
                ('iMinX', models.IntegerField()),
                ('iMinY', models.IntegerField()),
                ('iMaxX', models.IntegerField()),
                ('iMaxY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dimension7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g', models.CharField(max_length=20)),
                ('iMinX', models.IntegerField()),
                ('iMinY', models.IntegerField()),
                ('iMaxX', models.IntegerField()),
                ('iMaxY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dimension8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h', models.CharField(max_length=20)),
                ('iMinX', models.IntegerField()),
                ('iMinY', models.IntegerField()),
                ('iMaxX', models.IntegerField()),
                ('iMaxY', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='index',
        ),
        migrations.RemoveField(
            model_name='images',
            name='point',
        ),
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 3, 6, 21, 4, 15, 237308)),
        ),
        migrations.DeleteModel(
            name='dimension',
        ),
        migrations.DeleteModel(
            name='images',
        ),
    ]
