# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0019_auto_20180306_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension1',
            name='ob',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dimension2',
            name='ob',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dimension3',
            name='ob',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dimension4',
            name='ob',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dimension5',
            name='ob',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dimension6',
            name='ob',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dimension7',
            name='ob',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dimension8',
            name='ob',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 3, 6, 21, 16, 19, 799651)),
        ),
    ]
