# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0020_auto_20180306_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension1',
            name='ob',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dimension3',
            name='ob',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dimension4',
            name='ob',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dimension5',
            name='ob',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='dimension6',
            name='ob',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='dimension7',
            name='ob',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='dimension8',
            name='ob',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 3, 6, 21, 17, 24, 686230)),
        ),
    ]
