# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0021_auto_20180306_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 3, 6, 21, 20, 16, 898345)),
        ),
    ]
