# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0023_auto_20180306_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension1',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='show.level'),
        ),
        migrations.AlterField(
            model_name='dimension2',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='show.level'),
        ),
        migrations.AlterField(
            model_name='dimension3',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='show.level'),
        ),
        migrations.AlterField(
            model_name='dimension4',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='show.level'),
        ),
        migrations.AlterField(
            model_name='dimension5',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='show.level'),
        ),
        migrations.AlterField(
            model_name='dimension6',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='show.level'),
        ),
        migrations.AlterField(
            model_name='dimension7',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='show.level'),
        ),
        migrations.AlterField(
            model_name='dimension8',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='show.level'),
        ),
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 3, 11, 7, 50, 10, 218791)),
        ),
    ]
